config/routes.rb
Rails.application.routes.draw do


  # 顧客用
# URL /customers/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    resources :users, only: [:index, :edit, :update, :show]
    resources :teams, only: [:index, :edit, :update, :show]
    resources :players, only: [:index, :edit, :update, :show]
    resources :rooms, only: [:index, :show]
    get 'homes/top'
    resources :player_posts, only: [:index, :show, :destroy]
    resources :team_posts, only: [:index, :show, :destroy]
  end

  scope module: :public do
    get 'homes/top'
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    get 'homes/about'
    get 'users/unsubscribe'
    patch "users/withdrawal"
    post "team_posts/new/view" => "team_posts#new", as:"team_posts_new"
    resources :teams
    resources :player_posts
    resources :players, only: [:update, :edit, :show]
    resources :users, only: [:edit, :update, :show]
    resources :messages, only: [:create]
    resources :rooms, only: [:index, :show, :create]
    resources :favorite_teams, only: [:index]
    resources :favorite_players, only: [:index]
    resources :team_posts, only: [:index, :edit, :update, :create, :destroy, :show]
    root to: "homes#top"
    resources :player_posts do
      resource :favorite_players, only: [:create, :destroy]
    end
    resources :team_posts do
      resource :favorite_teams, only: [:create, :destroy]
    end
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to admin_player_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :telephone_number, :sex, :is_deleted, :age, :nickname, :introduction, :image, :password, :password_confirmation, :is_deleted)
  end

end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/views/admin/players/edit.html.erb
<p id="notice"></p>
<div class="container d-flex mt-4">
  <h4 class="bg-light">プロフィール編集画面</h4>
</div>

<%= form_with model: @user, url: admin_player_path(@user), method: :patch do |f| %>
 <div class="container mb-5" style="width: 80%">
  <div class="align-items-center justify-content-center">
    <div class="row">
      <table class="table table-borderless">
        <tr>
          <th>プロフィール画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= f.text_field :nickname %></td>
        </tr>
        <tr>
          <th>年齢</th>
          <td>
            <%= f.select :age, *[18..80], { prompt: "選択してください" } %>
          </td>
        </tr>
        <tr>
          <th>自己紹介</th>
          <td>
            <%= f.text_area :introduction, style: "width: 70%", rows: 5 %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="d-flex align-items-center justify-content-center">
    <div class="mr-4">
      <%= f.submit "　プロフィールを更新する　", class: "btn btn-success" %>
    </div>
  </div>
</div>
<% end %>

app/views/admin/players/show.html.erb
<p id="notice"></p>
<div class="container d-flex mt-4">
  <h4 class="bg-light"><%= @user.nickname %>さんのプロフィール</h4>
</div>

<div class="container mb-4">
  <div class="row">
    <div class="col-5">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, size: "200x200" %>
      <% else %>
        <%= image_tag 'default-image', size: "200x200" %>
      <% end %>
    </div>
    <div class="col-7">
      <table class="table">
        <tr>
          <th style="width :20%">名前(年齢)</th><td><%= @user.last_name %> <%= @user.first_name %>(<%= @user.age %>歳)</td>
        </tr>
        <tr>
          <th>ニックネーム</th><td><%= @user.nickname %></td>
        </tr>
        <tr>
          <th>性別</th>
          <td>
            <%= @user.sex_i18n %>
          </td>
        </tr>
        <tr>
          <th>自己紹介</th><td><%= @user.introduction %></td>
        </tr>
      </table>
      <div class="d-flex">
        <div class="mr-4 mb-10">
          <%= link_to "プロフィールを編集する", edit_admin_player_path, class: "btn btn-success" %>
        </div>
        <div>
          <%= link_to "会員情報詳細", admin_user_path(@user), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

  <div class="container index-post mt-3">
    <% if @user.teams.present? %>
    <div class="d-flex mt-4">
      <h4 class="bg-light">登録チーム</h4>
    </div>
    <div class="mt-4 team-list row d-flex">
        <% @user.teams.each do |team| %>
          <div class="mt-4 container team">
            <div class="row">
              <div class="text-l">
                <h4 class="space">チーム名</h4>
              </div>
              <div class="mb-4 text-l">
                <% if team.image.attached? %>
                  <%= image_tag team.image, size: "35x35" %>
                <% else %>
                  <%= image_tag 'default-image', size: "35x35" %>
                <% end %>
              </div>
              <div class="pb-2 ml-3 text-l mr-auto">
                <h4>
                  <%= link_to team.name, admin_team_path(team) %>
                </h4>
              </div>
              <div class="">
                <%= link_to "編集する", edit_admin_team_path(team), class: "btn btn-success" %>
              </div>
            </div>
          </div>
        <% end %>
    </div>
    <% end %>
  </div>