config/routes.rb
Rails.application.routes.draw do


  # 顧客用
# URL /customers/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    resources :users, only: [:index, :edit, :update, :show]
    resources :teams, only: [:index, :edit, :update, :show]
    resources :players, only: [:index, :edit, :update, :show]
    resources :rooms, only: [:index, :show]
    get 'homes/top'
    resources :player_posts, only: [:index, :show, :destroy]
    resources :team_posts, only: [:index, :show, :destroy]
  end

  scope module: :public do
    get 'homes/top'
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    get 'homes/about'
    get 'users/unsubscribe'
    patch "users/withdrawal"
    post "team_posts/new/view" => "team_posts#new", as:"team_posts_new"
    resources :teams
    resources :player_posts
    resources :players, only: [:update, :edit, :show]
    resources :users, only: [:edit, :update, :show]
    resources :messages, only: [:create]
    resources :rooms, only: [:index, :show, :create]
    resources :favorite_teams, only: [:index]
    resources :favorite_players, only: [:index]
    resources :team_posts, only: [:index, :edit, :update, :create, :destroy, :show]
    root to: "homes#top"
    resources :player_posts do
      resource :favorite_players, only: [:create, :destroy]
    end
    resources :team_posts do
      resource :favorite_teams, only: [:create, :destroy]
    end
  end
end

app/models/team_post.rb
class TeamPost < ApplicationRecord

  belongs_to :team
  has_many :favorite_teams, dependent: :destroy
  has_many :tag_teams, dependent: :destroy
  has_many :tags, through: :tag_teams

  validates :content, presence: true
  validates :post_type, presence: true
  validates :prefecture, presence: true
  validates :title, presence: true

  enum post_type: { recruitment: 0, helper: 1, game: 2 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def self.search(keyword)
    where(["content like? OR title like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/admin/team_post_controller.rb
class Admin::TeamPostController < ApplicationController
end

app/controllers/admin/team_posts_controller.rb
class Admin::TeamPostsController < ApplicationController
  before_action :admin_signed_in

  def index
    @team_posts = TeamPost.order("created_at DESC").page(params[:page])
    @tag_list = Tag.all
    if params[:tag_ids]
      @team_posts = [:name]
      params[:tag_ids].each do |key, value|
        @team_posts += Tag.find_by(name: key).tweets if value == "1"
      end
      @team_posts.uniq!
    end
  end

  def show
    @team_post = TeamPost.find(params[:id])
  end

  def destroy
    @team_post = TeamPost.find(params[:id])
    if @team_post.destroy
      redirect_to admin_team_posts_path
    else
      render :show
    end
  end

  def search
    @team_posts = TeamPost.search(params[:keyword]).page(params[:page])
    @keyword = params[:keyword]
    render "index"
  end

  def tag_search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @team_posts = @tag.team_posts.order("created_at DESC").page(params[:page])
  end

  private

  def admin_signed_in
    unless admin_signed_in?
      redirect_to new_admin_session_path
    end
  end

end

app/helpers/admin/team_post_helper.rb
module Admin::TeamPostHelper
end

app/views/admin/team_posts/index.html.erb
<div class="container d-flex mt-4 mb-4">
  <h4 class="bg-light">チーム投稿一覧</h4>
</div>

<div class="container">
  <div class="row">
    <div class="search-form col-3">
      <%= form_with url: admin_team_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
      <% end %>
    </div>

    <div class="col-7">
      <ul class="recruit-list">
        <% @team_posts.each do |team_post| %>
          <li class="recruit new_rec">
            <h4 class="align-middle mt-3">
              <%= link_to team_post.title, admin_team_post_path(team_post) %>
            </h4>
            <div class="author">チーム名: <%= link_to team_post.team.name, admin_team_path(team_post.team.id) %></div>
            <ol class="sub pb-2">
              <li>投稿種類: <%= team_post.post_type_i18n %></li>
              <li>活動場所: <%= team_post.prefecture %> > <%= team_post.city %></li>
            </ol>
            <div class="mb-10">
              <% team_post.tags.each do |tag| %>
                <span class="tag"><%= link_to tag.name, admin_team_tag_search_path(tag_id: tag.id) %></span>
              <% end %>
            </div>
          </li>
        <% end %>
        <%= paginate @team_posts %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/team_posts/show.html.erb
<p id="notice"></p>
<div class="container d-flex mb-3">
  <h4 class="bg-light">投稿詳細</h4>
</div>

<div class="container mb-4">
  <div class="row">
    <div class="col-5">
      <% if @team_post.team.image.attached? %>
        <%= image_tag @team_post.team.image, size: "200x200" %>
      <% else %>
        <%= image_tag 'default-image', size: "200x200" %>
      <% end %>
    </div>
    <div class="col-6">
      <table class="table">
        <tr>
          <th style="width :25%">チーム名</th><td><%= @team_post.team.name %></td>
        </tr>
        <tr>
          <th>投稿者</th><td><%= @team_post.team.user.last_name %></td>
        </tr>
        <tr>
          <th>投稿種類</th><td><%= @team_post.post_type_i18n %></td>
        </tr>
        <tr>
          <th>活動エリア</th><td><%= @team_post.prefecture %> > <%= @team_post.city %></td>
        </tr>
        <tr>
          <th>本文</th><td><%= @team_post.content %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class"container mt-4">
  <div class="d-flex align-items-center justify-content-center">
    <%= link_to "投稿を削除する", admin_team_post_path(@team_post.id), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/team_posts/tag_search.html.erb
<div class="container d-flex mt-4 mb-4">
  <h4 class="bg-light">チーム投稿一覧(タグ検索)</h4>
</div>

<div class="container">
  <div class="row">
    <div class="search-form col-3">
      <%= form_with url: team_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
      <% end %>
    </div>

    <div class="col-7">
      <ul class="recruit-list">
        <% @team_posts.each do |team_post| %>
          <li class="recruit new_rec">
            <h4 class="align-middle mt-3">
              <%= link_to team_post.title, team_post_path(team_post) %>
            </h4>
            <div class="author">チーム名: <%= link_to team_post.team.name, team_path(team_post.team.id) %></div>
            <ol class="sub pb-2">
              <li>投稿種類: <%= team_post.post_type_i18n %></li>
              <li>活動場所: <%= team_post.prefecture %> > <%= team_post.city %></li>
            </ol>
            <div>
            <% if user_signed_in? %>
              <ol class="text-l">
                <% team_post.tags.each do |tag| %>
                  <span class="tag"><%= link_to tag.name, team_tag_search_path(tag_id: tag.id) %></span>
                <% end %>
              </ol>
              <h5 class="text-r heart mb-3">
                お気に入り
                <% if current_user.already_team_favorited?(team_post) %>
                  <%= link_to team_post_favorite_teams_path(team_post), method: :delete do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to team_post_favorite_teams_path(team_post), method: :post do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
              </h5>
            <% else %>
              <h5 class="mb-3">
                <% team_post.tags.each do |tag| %>
                  <span class="tag"><%= link_to tag.name, team_tag_search_path(tag_id: tag.id) %></span>
                <% end %>
              </h5>
            <% end %>
            </div>
          </li>
        <% end %>
        <%= paginate @team_posts %>
      </ul>
    </div>
  </div>
</div>