config/routes.rb
Rails.application.routes.draw do


  # 顧客用
# URL /customers/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    resources :users, only: [:index, :edit, :update, :show]
    resources :teams, only: [:index, :edit, :update, :show]
    resources :players, only: [:index, :edit, :update, :show]
    resources :rooms, only: [:index, :show]
    get 'homes/top'
    resources :player_posts, only: [:index, :show, :destroy]
    resources :team_posts, only: [:index, :show, :destroy]
  end

  scope module: :public do
    get 'homes/top'
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    get 'homes/about'
    get 'users/unsubscribe'
    patch "users/withdrawal"
    post "team_posts/new/view" => "team_posts#new", as:"team_posts_new"
    resources :teams
    resources :player_posts
    resources :players, only: [:update, :edit, :show]
    resources :users, only: [:edit, :update, :show]
    resources :messages, only: [:create]
    resources :rooms, only: [:index, :show, :create]
    resources :favorite_teams, only: [:index]
    resources :favorite_players, only: [:index]
    resources :team_posts, only: [:index, :edit, :update, :create, :destroy, :show]
    root to: "homes#top"
    resources :player_posts do
      resource :favorite_players, only: [:create, :destroy]
    end
    resources :team_posts do
      resource :favorite_teams, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enter.rb
class Enter < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/favorite_player.rb
class FavoritePlayer < ApplicationRecord
  
  belongs_to :user
  belongs_to :player_post
  
  validates_uniqueness_of :player_post_id, scope: :user_id
end

app/models/favorite_team.rb
class FavoriteTeam < ApplicationRecord

  belongs_to :user
  belongs_to :team_post

  validates_uniqueness_of :team_post_id, scope: :user_id

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :content, presence: true

  def self.search(keyword)
    where(["content like? OR title like?", "%#{keyword}%", "%#{keyword}%"])
  end

  def room_has_current_user_id
    @rooms = Room.all
    @room = @rooms.each do |room|
      @enters = room.enter.all

    end
  end
end

app/models/player_post.rb
class PlayerPost < ApplicationRecord

  belongs_to :user
  has_many :favorite_players, dependent: :destroy
  has_many :tag_players, dependent: :destroy
  has_many :tags, through: :tag_players

  validates :title, presence: true
  validates :content, presence: true
  validates :post_type, presence: true
  validates :prefecture, presence: true
  validates :position, presence: true

  enum post_type: { join_team: 0, helper: 1 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def self.search(keyword)
    where(["content like? OR title like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :enters, dependent: :destroy
  has_many :users, through: :enters

  def self.search(keyword)
    where(["messages.content like?", "%#{keyword}%"])
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_teams, dependent: :destroy, foreign_key: 'tag_id'
  has_many :tag_players, dependent: :destroy, foreign_key: 'tag_id'
  has_many :team_posts, through: :tag_teams
  has_many :player_posts, through: :tag_players

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/tag_player.rb
class TagPlayer < ApplicationRecord
  
  belongs_to :player_post
  belongs_to :tag
end

app/models/tag_team.rb
class TagTeam < ApplicationRecord
  
  belongs_to :team_post
  belongs_to :tag
end

app/models/team.rb
class Team < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :team_posts, dependent: :destroy

  validates :name, presence: true
  validates :age, presence: true
  validates :introduction, presence: true
  validates :user_id, presence: true
end

app/models/team_post.rb
class TeamPost < ApplicationRecord

  belongs_to :team
  has_many :favorite_teams, dependent: :destroy
  has_many :tag_teams, dependent: :destroy
  has_many :tags, through: :tag_teams

  validates :content, presence: true
  validates :post_type, presence: true
  validates :prefecture, presence: true
  validates :title, presence: true

  enum post_type: { recruitment: 0, helper: 1, game: 2 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def self.search(keyword)
    where(["content like? OR title like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image

  has_many :teams, dependent: :destroy
  has_many :favorite_players, dependent: :destroy
  has_many :favorite_teams, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :enters, dependent: :destroy
  has_many :player_posts, dependent: :destroy
  has_many :rooms, through: :enters
  has_many :team_posts, through: :teams, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }, presence: true
  validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }, presence: true
  validates :sex, presence: true
  validates :age, presence: true
  validates :telephone_number, format: { with: /\A\d{10,11}\z/ }, presence: true
  validates :is_deleted, inclusion: {in: [true, false]}

  enum sex: { male: 0, female: 1 }

  def already_team_favorited?(team_post)
    self.favorite_teams.exists?(team_post_id: team_post.id)
  end

  def already_player_favorited?(player_post)
    self.favorite_players.exists?(player_post_id: player_post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    added_attrs = [:last_name, :first_name, :last_name_kana, :first_name_kana, :sex, :age, :telephone_number, :is_deleted, :nickname, :introduction, :image, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
  
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseballMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/b1b4139a9c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <p id="notice"></p>
    <header class="border-bottom">
      <div class="container">
        <div class="row d-flex mb-4">
          <div class="mr-auto"><%= link_to "BaseballMate", root_path, class: "btn border", style: "height: 40px" %></div>
          <% if !user_signed_in? && !admin_signed_in? %>
            <div class="title"><%= link_to "ログイン", new_user_session_path, method: :get, class: "btn border" %></div>
            <div class="title"><%= link_to "新規登録", new_user_registration_path, class: "btn border" %></div>
          <% elsif user_signed_in? && !admin_signed_in? %>
            <div class="title"><%= link_to "マイページ", player_path(current_user), class: "btn border" %></div>
            <div class="title"><%= link_to "会員情報", user_path(current_user), class: "btn border" %></div>
            <div class="title"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn border" %></div>
          <% elsif admin_signed_in? %>
            <div class="title"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn border" %></div>
          <% end %>
        </div>
        <nav class="row d-flex" style="height:50">
        <% if admin_signed_in? %>
          <li class="list"><%= link_to "チーム一覧", admin_teams_path, class: "btn" %></li>
          <li class="title list"><%= link_to "ユーザー一覧", admin_users_path, class: "btn" %></li>
          <li class="title list"><%= link_to "チーム投稿", admin_team_posts_path, class: "btn" %></li>
          <li class="title list"><%= link_to "選手投稿", admin_player_posts_path, class: "btn" %></li>
          <li class="title list"><%= link_to "メッセージ一覧", admin_rooms_path, class: "btn" %></li>
        <% elsif user_signed_in? && !admin_signed_in? %>
          <li class="list"><%= link_to "チーム投稿", team_posts_path, class: "btn" %></li>
          <li class="title list"><%= link_to "選手投稿", player_posts_path, class: "btn" %></li>
          <li class="title list"><%= link_to "お気に入りチーム投稿", favorite_teams_path, class: "btn" %></li>
          <li class="title list"><%= link_to "お気に入り選手投稿", favorite_players_path, class: "btn" %></li>
          <li class="title list"><%= link_to "メッセージ一覧", rooms_path, class: "btn" %></li>
        <% elsif !user_signed_in? && !admin_signed_in? %>
                    <li class="list"><%= link_to "チーム投稿", team_posts_path, class: "btn" %></li>
          <li class="title list"><%= link_to "選手投稿", player_posts_path, class: "btn" %></li>
        <% end %>

        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>