config/routes.rb
Rails.application.routes.draw do


  # 顧客用
# URL /customers/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    resources :users, only: [:index, :edit, :update, :show]
    resources :teams, only: [:index, :edit, :update, :show]
    resources :players, only: [:index, :edit, :update, :show]
    resources :rooms, only: [:index, :show]
    get 'homes/top'
    resources :player_posts, only: [:index, :show, :destroy]
    resources :team_posts, only: [:index, :show, :destroy]
  end

  scope module: :public do
    get 'homes/top'
    get 'team_search' => 'team_posts#search'
    get 'player_search' => 'player_posts#search'
    get 'team_tag_search' => 'team_posts#tag_search'
    get 'player_tag_search' => 'player_posts#tag_search'
    get 'homes/about'
    get 'users/unsubscribe'
    patch "users/withdrawal"
    post "team_posts/new/view" => "team_posts#new", as:"team_posts_new"
    resources :teams
    resources :player_posts
    resources :players, only: [:update, :edit, :show]
    resources :users, only: [:edit, :update, :show]
    resources :messages, only: [:create]
    resources :rooms, only: [:index, :show, :create]
    resources :favorite_teams, only: [:index]
    resources :favorite_players, only: [:index]
    resources :team_posts, only: [:index, :edit, :update, :create, :destroy, :show]
    root to: "homes#top"
    resources :player_posts do
      resource :favorite_players, only: [:create, :destroy]
    end
    resources :team_posts do
      resource :favorite_teams, only: [:create, :destroy]
    end
  end
end

app/models/player_post.rb
class PlayerPost < ApplicationRecord

  belongs_to :user
  has_many :favorite_players, dependent: :destroy
  has_many :tag_players, dependent: :destroy
  has_many :tags, through: :tag_players

  validates :title, presence: true
  validates :content, presence: true
  validates :post_type, presence: true
  validates :prefecture, presence: true
  validates :position, presence: true

  enum post_type: { join_team: 0, helper: 1 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def self.search(keyword)
    where(["content like? OR title like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/admin/player_posts_controller.rb
class Admin::PlayerPostsController < ApplicationController
  before_action :admin_signed_in

  def index
    @player_posts = PlayerPost.order("created_at DESC").page(params[:page])
    @tag_list = Tag.all
    if params[:tag_ids]
      @player_posts = [:name]
      params[:tag_ids].each do |key, value|
        @player_posts += Tag.find_by(name: key).tweets if value == "1"
      end
      @player_posts.uniq!
    end
  end

  def show
    @player_post = PlayerPost.find(params[:id])
  end

  def destroy
    @player_post = PlayerPost.find(params[:id])
    if @player_post.destroy
      redirect_to admin_player_posts_path
    else
      render :show
    end
  end

  def search
    @player_posts = PlayerPost.search(params[:keyword]).page(params[:page])
    @keyword = params[:keyword]
    render "index"
  end

  def tag_search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @player_posts = @tag.player_posts.order("created_at DESC").page(params[:page])
  end

  def admin_signed_in
    unless admin_signed_in?
      redirect_to new_admin_session_path
    end
  end
end

app/helpers/admin/player_posts_helper.rb
module Admin::PlayerPostsHelper
end

app/views/admin/player_posts/index.html.erb
<div class="container d-flex mt-4 mb-4">
  <h4 class="bg-light">選手投稿一覧</h4>
</div>

<div class="container">
  <div class="row">
    <div class="search-form col-3">
      <%= form_with url: player_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
      <% end %>
    </div>

    <div class="col-7">
      <ul class="recruit-list">
        <% @player_posts.each do |player_post| %>
          <li class="recruit new_rec">
            <h4 class="align-middle mt-3">
              <%= link_to player_post.title, admin_player_post_path(player_post) %>
            </h4>
            <div class="author">
              投稿者:
              <% if player_post.user.nickname.present? %>
                <%= link_to player_post.user.nickname, admin_user_path(player_post.user) %>
              <% else %>
                <%= link_to admin_user_path(player_post.user) do %>
                  <%= player_post.user.last_name %> <%= player_post.user.first_name %>
                <% end %>
              <% end %>
            </div>
            <ol class="sub pb-2">
              <li>投稿種類: <%= player_post.post_type_i18n %></li>
              <li>活動場所: <%= player_post.prefecture %> > <%= player_post.city %></li>
            </ol>
            <div class="mb-10">
              <% player_post.tags.each do |tag| %>
                <span class="tag"><%= link_to tag.name, player_tag_search_path(tag_id: tag.id) %></span>
              <% end %>
            </div>
          </li>
        <% end %>
        <%= paginate @player_posts %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/player_posts/show.html.erb
<p id="notice"></p>
<div class="container d-flex pl-4 mb-3">
  <h4 class="bg-light">投稿詳細</h4>
</div>

<div class="container mb-4">
  <div class="row">
    <div class="col-5">
      <% if @player_post.user.image.attached? %>
        <%= image_tag @player_post.user.image, size: "200x200" %>
      <% else %>
        <%= image_tag 'default-image', size: "200x200" %>
      <% end %>
    </div>
    <div class="col-6">
      <table class="table">
        <tr>
          <th>投稿者</th><td><%= @player_post.user.last_name %></td>
        </tr>
        <tr>
          <th>投稿種類</th><td><%= @player_post.post_type_i18n %></td>
        </tr>
          <th>活動エリア</th><td><%= @player_post.prefecture %> > <%= @player_post.city %></td>
        </tr>
        <tr>
          <th>本文</th><td><%= @player_post.content %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class"container mt-4">
  <div class="d-flex align-items-center justify-content-center">
    <%= link_to "投稿を削除する", admin_player_post_path(@player_post.id), method: :delete, data: {confirm: "投稿を削除しますか？"}, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/player_posts/tag_search.html.erb
<div class="container d-flex mt-4 mb-4">
  <h4 class="bg-light">選手投稿一覧(タグ検索)</h4>
</div>

<div class="container">
  <div class="row">
    <div class="search-form col-3">
      <%= form_with url: admin_player_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
      <% end %>
    </div>

     <div class="col-7">
      <ul class="recruit-list">
        <% @player_posts.each do |player_post| %>
          <li class="recruit new_rec">
            <h4 class="align-middle mt-3">
              <%= link_to player_post.title, admin_player_post_path(player_post) %>
            </h4>
            <div class="author">
              投稿者:
              <% if player_post.user.nickname.present? %>
                <%= link_to player_post.user.nickname, admin_user_path(player_post.user) %>
              <% else %>
                <%= link_to admin_player_path(player_post.user) do %>
                  <%= player_post.user.last_name %> <%= player_post.user.first_name %>
                <% end %>
              <% end %>
            </div>
            <ol class="sub pb-2">
              <li>投稿種類: <%= player_post.post_type_i18n %></li>
              <li>活動場所: <%= player_post.prefecture %> > <%= player_post.city %></li>
            </ol>
            <div>
              <ol class="mb-3">
                <% player_post.tags.each do |tag| %>
                  <span class="tag"><%= link_to tag.name, admin_player_tag_search_path(tag_id: tag.id) %></span>
                <% end %>
              </ol>
            </div>
          </li>
        <% end %>
        <%= paginate @player_posts %>
      </ul>
    </div>
  </div>
</div>